name: kiran_portfolio
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^10.1.0+1
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  duration: ^4.0.3
  flash: ^3.1.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  particles_network: ^1.8.0
  blurrycontainer: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_animate_on_scroll: ^0.3.0
  animated_flip_counter: ^0.3.4
  flutter_gen: ^5.11.0
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.1.1
  liquid_glass_renderer: ^0.1.1-dev.21
  animated_digit: ^3.3.1+2
  cross_file: ^0.3.4+2
  firebase_core:
  firebase_storage: ^13.0.0
  flip_card: ^0.7.0
  glass_kit: ^4.0.1
  flutter_social_button: ^1.1.6+1
  gap: ^3.0.1

  selectable: null
  permission_handler: ^11.3.1
  hovering: ^1.0.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage_x: ^11.3.0
  hive_ce_flutter: ^2.3.1
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2
  multiple_result: ^5.2.0
  path_provider: ^2.1.5
  platform_info: ^5.0.0
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker_dio_logger: ^4.9.3
  talker_flutter: ^4.9.3
  talker_riverpod_logger: ^4.9.3
  velocity_x:
    git:
      url: https://github.com/Shreemanarjun/VelocityX.git
      ref: stable
  font_awesome_flutter: ^10.9.0
  cached_network_image: ^3.4.1
  particles_fly: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.6
  custom_lint: ^0.7.6  # ✅ fix version conflict
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.5
  riverpod_test: ^0.1.9
  slang_build_runner: ^4.8.0
  spot: ^0.18.0
  very_good_analysis: ^9.0.0



flutter_gen:
  output: lib/core/gen/
  # line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case
      # Assets.images_chip
      # style: snake-case
      # Assets.images.chip (default style)
      style: dot-delimiter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tools_images/
    - assets/images/service_images/
    - assets/pdf/
  fonts:
    - family: Agustina
      fonts:
        - asset: assets/fonts/agustina/agustina.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic




